version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - ./chromadb_data:/chroma/chroma  # Persistent storage for Chroma memory
    restart: always
